version: '3.8'

services:
  redis-node:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
    restart: always
    ports:
      - '6379:6379'

  redis-node2: 
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.2'
    restart: always
    ports:
      - '6380:6379'

  redis-node3:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node 127.0.0.1 127.0.0.2'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.3'
    restart: always
    ports:
      - '6381:6379'