services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    volumes:
      - meilisearch_data:/data.ms
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  meilisearch_data: